AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Combined SAM template for HRMS Notification Prod functions.

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 2048 # Increased for production
    Timeout: 30 # Adjusted for production
    Environment:
      Variables:
        SQS_QUEUE_URL: !Ref NotificationQueue
        SNS_CREATE_NOTIFICATION_TOPIC: !Ref SnsTopicCreateNotificationARN
        SNS_BROADCAST_TOPIC_ARN: !Ref SnsTopicBroadcastNotificationARN
        DB_NOTIFICATION: !Ref NotificationDB
        DB_EMPLOYEE: !Ref EmployeeDB
        DB_VACANCY: !Ref VacancyDB
        DB_WS_CONNECTION: !Ref ConnectionDB
        DB_CANDIDATE: !Ref CandidateDB
        ATLAS_ACCESS: !Ref AtlasAccess

Parameters:
  StageEnv:
    Type: String
    Default: prod # Changed to prod
  AtlasAccess:
    Type: String
  VPCSecurityGroup:
    Type: String
  VPCSubnet1:
    Type: String
  VPCSubnet2:
    Type: String
  AuthorizerARN:
    Type: String
  NotificationDB:
    Type: String
  EmployeeDB:
    Type: String
  VacancyDB:
    Type: String
  ConnectionDB:
    Type: String
  CandidateDB:
    Type: String
  SnsTopicBroadcastNotificationARN:
    Type: String
  SnsTopicCreateNotificationARN:
    Type: String

Resources:
  # SQS Queue
  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: doCreateNotification_queue

  # SQS Queue Policy
  NotificationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref NotificationQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 'sqs:SendMessage'
            Resource: !GetAtt NotificationQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SnsTopicCreateNotificationARN

  # SNS Topic Subscription
  NotificationTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Ref SnsTopicCreateNotificationARN
      Endpoint: !GetAtt NotificationQueue.Arn

  # API Gateway
  HRMSNotificationProdAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageEnv
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CoreAuthorizer
        Authorizers:
          CoreAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !Ref AuthorizerARN
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
        AddDefaultAuthorizerToCorsPreflight: False

  # Lambda Function for HRMS
  HRMSNotificationProdLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambda.handler
      CodeUri: ./.serverless/build/app.zip
      Policies:
        - arn:aws:iam::730335295088:policy/LambdaWithPrivateLinkExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
                - sqs:SendMessage
              Resource:
                - !Ref SnsTopicCreateNotificationARN
                - !Ref SnsTopicBroadcastNotificationARN
                - !GetAtt NotificationQueue.Arn

      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
      AutoPublishAlias: !Ref StageEnv
      SnapStart:
        ApplyOn: None
      Events:
        RestApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref HRMSNotificationProdAPI

  # Lambda Function for SQS
  SQSHandlerProdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/notification-builder/sqs.handler
      CodeUri: ./.serverless/build/app.zip
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCSecurityGroup
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:ReceiveMessage'
                - 'sqs:DeleteMessage'
                - 'sqs:GetQueueAttributes'
              Resource: !GetAtt NotificationQueue.Arn
        - Statement:
            Effect: Allow
            Action: 'sns:Publish'
            Resource:
              - !Ref SnsTopicCreateNotificationARN
              - !Ref SnsTopicBroadcastNotificationARN
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NotificationQueue.Arn
            BatchSize: 5

Outputs:
  HRMSNotificationProdEndpoint:
    Description: API Gateway HRMS Notification Prod
    Value:
      Fn::Sub: https://${HRMSNotificationProdAPI}.execute-api.${AWS::Region}.amazonaws.com/${StageEnv}/

  QueueUrl:
    Description: URL of the SQS Queue
    Value: !Ref NotificationQueue
    Export:
      Name: NotificationQueueUrl

  QueueArn:
    Description: ARN of the SQS Queue
    Value: !GetAtt NotificationQueue.Arn
    Export:
      Name: NotificationQueueArn
